apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample1
  namespace: test-run
  labels:
    app: nginx
    ver: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      ver: v1 
  template:
    metadata:
      labels:
        app: nginx
        ver: v1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

