apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox1
  namespace: test-run
  labels:
    app: busybox1
    ver: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: busybox1
      ver: v1
  template:
    metadata:
      labels:
        app: busybox1
        ver: v1
    spec:
      containers:
      - name: busybox 
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c","while [ true ] ; do sleep 1 ; date ; date +%s >> /logs/log.file ; done"]
        volumeMounts:
        - mountPath: /logs
          name: logs
      - name: logs 
        image: busybox:latest
        command: ["/bin/sh"]
        args: ["-c","tail -f /logs/log.file"]
        volumeMounts:
        - mountPath: /logs
          name: logs
      volumes:
      - emptyDir: {}
        name: logs
